import { PredictionModelWeights } from '@/types/football';

export const DEFAULT_PREDICTION_WEIGHTS: PredictionModelWeights = {
  recentForm: 0.25,
  homeAwayPerformance: 0.20,
  attackStrength: 0.15,
  defensiveStrength: 0.15,
  headToHead: 0.10,
  leaguePosition: 0.10,
  goalDifference: 0.05,
};

export const MODEL_VERSION = 'v2.4-HybridPoisson';

export const PREDICTION_DISCLAIMER =
  'Predictions are statistical estimates generated by algorithmic models based on available team form, performance ratings, and historical head-to-head records. They are NOT guaranteed results and must never be considered financial, betting, or legal advice.';

export function getStoredWeights(): PredictionModelWeights {
  if (typeof window === 'undefined') return DEFAULT_PREDICTION_WEIGHTS;
  try {
    const raw = localStorage.getItem('goalpredict_model_weights');
    if (raw) {
      const parsed = JSON.parse(raw);
      // Validate sum roughly equals 1
      const total =
        (parsed.recentForm || 0) +
        (parsed.homeAwayPerformance || 0) +
        (parsed.attackStrength || 0) +
        (parsed.defensiveStrength || 0) +
        (parsed.headToHead || 0) +
        (parsed.leaguePosition || 0) +
        (parsed.goalDifference || 0);
      if (Math.abs(total - 1.0) < 0.05) {
        return parsed;
      }
    }
  } catch {
    // fallback
  }
  return DEFAULT_PREDICTION_WEIGHTS;
}

export function saveStoredWeights(weights: PredictionModelWeights): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem('goalpredict_model_weights', JSON.stringify(weights));
  } catch {
    // ignore
  }
}
